inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true

  Exclude:
    - 'bin/*'
    - db/schema.rb

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
  Exclude:
    - test/**/*

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false